GET http://localhost:8080/api/videos HTTP/1.1
###
POST http://localhost:8080/api/videos HTTP/1.1
content-type: application/json

{
    "title":"Cool NewReq",
    "description":"PUT IN",
    "url":"https://www.youtube.com/embed/C6MOKXm8x50",
    "author":{
        "firstname":"Aleksey",
        "lastname":"Bodrov",
        "age":32,
        "email":"lex.101@mail.ru"
    }
}
###
POST http://localhost:8080/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=pragmatic
&password=reviews
###
GET http://localhost:8080/api/videos HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHJhZ21hdGljIiwiYWRtaW4iOnRydWUsImV4cCI6MTY0MDY5MzAyMywiaWF0IjoxNjQwNDMzODIzLCJpc3MiOiJwcmFnbWF0aWNyZXZpZXdzLmNvbSJ9.47W1HXZwy3wbba_CfmN7ExvelMs7A7lgSLS5G6f5cU4
###
POST http://localhost:8080/api/videos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHJhZ21hdGljIiwiYWRtaW4iOnRydWUsImV4cCI6MTY0MDY5MzAyMywiaWF0IjoxNjQwNDMzODIzLCJpc3MiOiJwcmFnbWF0aWNyZXZpZXdzLmNvbSJ9.47W1HXZwy3wbba_CfmN7ExvelMs7A7lgSLS5G6f5cU4

{
    "title":"Cool NReq",
    "description":"PUT IN",
    "url":"https://www.youtube.com/embed/C6MOKXm8x50",
    "author":{
        "firstname":"Aleksey",
        "lastname":"Bodrov",
        "age":32,
        "email":"lex.1011@mail.ru"
    }
}
###
PUT  http://localhost:8080/api/videos/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHJhZ21hdGljIiwiYWRtaW4iOnRydWUsImV4cCI6MTY0MDY5MzAyMywiaWF0IjoxNjQwNDMzODIzLCJpc3MiOiJwcmFnbWF0aWNyZXZpZXdzLmNvbSJ9.47W1HXZwy3wbba_CfmN7ExvelMs7A7lgSLS5G6f5cU4

{
    "title":"Cool NRequest",
    "description":"PUT IN down",
    "url":"https://www.youtube.com/embed/C6MOKXm8x50",
    "author":{
        "id":1,
        "firstname":"Aleksey",
        "lastname":"Bodrov",
        "age":31,
        "email":"lex.101@mail.ru"
    }
}
###
DELETE   http://localhost:8080/api/videos/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoicHJhZ21hdGljIiwiYWRtaW4iOnRydWUsImV4cCI6MTY0MDY5MzAyMywiaWF0IjoxNjQwNDMzODIzLCJpc3MiOiJwcmFnbWF0aWNyZXZpZXdzLmNvbSJ9.47W1HXZwy3wbba_CfmN7ExvelMs7A7lgSLS5G6f5cU4
